version: '3.7'

services:
  frontend:
    image: imageName
    restart: always
    ports:
      - 3000:80
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      placement:
        constraints:
          - node.role == worker
    networks:
      - overlay_network

  backend:
    image: imageName
    restart: always
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      placement:
        constraints:
          - node.role == worker
    networks:
      - overlay_network

  mysql:
    image: mysql/mysql-server:5.7
    command: --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_DATABASE: employeeSystem
      MYSQL_ROOT_PASSWORD: mauFJcuf5dhRMQrjj
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql_server_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
    networks:
      - overlay_network

volumes: 
  mysql_server_data:

networks:
  overlay_network:
    driver: overlay